import VoiceAgent from "@/components/VoiceAgent";

const features = [
  ["01", "Natural voice conversations", "Explore how conversational AI can guide appointment requests."],
  ["02", "Appointment workflow", "Walk through fictional availability and slot selection."],
  ["03", "Vercel-ready foundation", "A Next.js app with an API health endpoint."]
];
const slots = ["Monday · 10:00 AM", "Tuesday · 2:00 PM", "Wednesday · 4:00 PM"];

export default function Home() {
  return <main className="min-h-screen overflow-hidden">
    <header className="shell flex h-[78px] items-center justify-between border-b border-white/10">
      <a href="#" className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl border border-indigo-300/25 bg-indigo-400/10 font-black text-indigo-200">SK</span><span><b className="block text-sm">SK DEV TEAM</b><small className="block text-[10px] tracking-widest text-slate-500">AI SYSTEMS LAB</small></span></a>
      <nav className="hidden gap-6 text-xs text-slate-400 sm:flex"><a href="#features">Capabilities</a><a href="#demo">Live demo</a><a href="#architecture">Architecture</a></nav>
      <a className="btn" href="#demo">Try the demo ↗</a>
    </header>
    <section className="shell grid items-center gap-12 py-20 md:grid-cols-2 md:py-28">
      <div><p className="label text-emerald-300">● Voice automation · Practice project</p><h1 className="mt-7 text-5xl font-semibold leading-tight tracking-tight sm:text-6xl md:text-7xl">A smarter way to <span className="gradient">book the next</span> appointment.</h1><p className="mt-6 max-w-xl text-base leading-7 text-slate-400">Meet an AI receptionist built to explore natural voice conversations, appointment workflows, and business automation.</p><div className="mt-8 flex flex-wrap gap-3"><a className="btn" href="#demo">Explore voice demo →</a><a className="ghost" href="#architecture">How it works</a></div><p className="mt-8 text-xs text-slate-500">Demo environment · Next.js + Vercel · ElevenLabs-ready</p></div>
      <div className="glass rounded-[26px] p-6"><div className="flex items-center justify-between border-b border-white/10 pb-5"><div><p className="text-sm font-semibold">Receptionist console</p><p className="mt-1 text-xs text-slate-500">Practice environment / 001</p></div><span className="rounded-full border border-emerald-300/20 px-3 py-1.5 text-[10px] text-emerald-300">DEMO MODE</span></div><div className="py-8 text-center"><div className="mx-auto grid h-28 w-28 place-items-center rounded-full border border-indigo-300/20 bg-indigo-400/10 text-4xl text-indigo-200">✳</div><p className="mt-5 font-semibold">Your AI receptionist</p><p className="mt-2 text-xs text-slate-500">Ready to demonstrate a conversation</p></div><div className="rounded-xl border border-white/10 bg-white/[.03] p-4"><p className="text-[10px] text-indigo-300">AI RECEPTIONIST</p><p className="mt-2 text-sm leading-6 text-slate-300">Hello! Would you like to practice booking an appointment?</p></div><div className="ml-7 mt-3 rounded-xl border border-indigo-300/15 bg-indigo-400/[.08] p-4"><p className="text-[10px] text-slate-500">EXAMPLE CALLER</p><p className="mt-2 text-sm text-slate-300">I would like to see available times.</p></div></div>
    </section>
    <section id="features" className="shell border-t border-white/10 py-16"><p className="label">Built for real-world workflows</p><h2 className="mt-3 text-3xl font-semibold">Small demo. <span className="text-slate-500">Serious foundation.</span></h2><div className="mt-8 grid gap-4 md:grid-cols-3">{features.map(([n,t,d])=><article className="card" key={n}><p className="text-xs text-indigo-300">{n}</p><h3 className="mt-5 font-semibold">{t}</h3><p className="mt-3 text-sm leading-6 text-slate-400">{d}</p></article>)}</div></section>
    <section id="demo" className="shell grid gap-8 border-t border-white/10 py-16 md:grid-cols-2"><div><p className="label">Interactive sandbox</p><h2 className="mt-3 text-3xl font-semibold">Meet the receptionist.</h2><p className="mt-4 text-sm leading-7 text-slate-400">Configure an ElevenLabs agent to enable voice interaction.</p><div className="mt-6 rounded-xl border border-amber-300/20 bg-amber-200/[.04] p-4"><b className="text-sm text-amber-200">Practice only</b><p className="mt-2 text-xs leading-5 text-slate-400">No real appointments are created or stored. Do not enter private medical or payment information.</p></div><p className="label mt-7">Sample availability</p><div className="mt-3 space-y-2">{slots.map(s=><div className="flex items-center gap-3 rounded-xl border border-white/10 p-3" key={s}><span className="h-2 w-2 rounded-sm bg-indigo-400"/><span className="text-sm text-slate-300">{s}</span><span className="ml-auto text-[10px] text-slate-600">SAMPLE</span></div>)}</div></div><div className="glass h-fit rounded-2xl p-6"><p className="font-semibold">Voice agent</p><p className="mb-5 mt-1 text-xs text-slate-500">ElevenLabs integration</p><VoiceAgent/></div></section>
    <section id="architecture" className="shell border-t border-white/10 py-16"><p className="label">Architecture preview</p><h2 className="mt-3 text-3xl font-semibold">From voice to workflow.</h2><p className="mt-4 max-w-2xl text-sm leading-7 text-slate-400">Planned flow: voice conversation → validated server-side tool → availability check → database. The backend and database are not yet connected in this demo.</p><div className="mt-7 grid gap-3 sm:grid-cols-4">{[["01","Caller","Speaks naturally"],["02","ElevenLabs","Handles conversation"],["03","Secure API","Validates action"],["04","Database","Stores confirmed data"]].map(([n,t,d])=><article className="card" key={n}><p className="text-xs text-indigo-300">{n}</p><h3 className="mt-4 font-semibold">{t}</h3><p className="mt-2 text-xs text-slate-500">{d}</p></article>)}</div></section>
    <footer className="border-t border-white/10"><div className="shell flex flex-col gap-3 py-7 text-xs text-slate-500 sm:flex-row sm:justify-between"><p>© 2026 SK DEV TEAM · Learning demo</p><div className="flex gap-5"><a href="https://github.com/suhailahmedaamro786/ai-appointment-booking-agent">GitHub ↗</a><a href="/api/health">API health ↗</a></div></div></footer>
  </main>;
}
